### ISSUE TITLE
Pop-up window needs to be scrolled

### ISSUE THREAD

**Issue by me4175** [Rayquaza01/authenticator#1]
When clicking on the key icon in the toolbar, the lines are not fully shown and need to be scrolled to the right in order to see the copy icon. I'm running Firefox 55.0b1 on Windows 10 Insider build 16199.
![2017-06-16 15_43_55-new issue rayquaza01_authenticator](https://user-images.githubusercontent.com/22673177/27219105-a5247b98-52aa-11e7-936b-e0c50dd4e41c.png)

**Comment by Rayquaza01** [comment]
The newest version (1.0.4) should fix this. I just submitted it to AMO now, so it could take a while to be reviewed. Let me know if it works correctly after you get it.

**Comment by me4175** [comment]
It’s working fine now, thanks.
