### ISSUE TITLE
Popup disappears immediately

### ISSUE THREAD

**Issue by sirfz** [Rayquaza01/authenticator#16]
## Bug Report

Please fill out this information:
 * Browser version: Firefox 63.0
 * Extension version: 1.2.0
 * Operating system: Ubuntu 18.04

---

What is happening?
When I click the extension icon, the pop-up appears briefly and immediately disappears so I can't interact with it at all.

---

What are the steps to reproduce the bug?
Click icon

---

Open the browser console (Hamburger menu > Web Developer > Browser Console) and include anything that is logged when the bug occurs.  
This step is not always necessary.

I see `Invalid chrome URI: /` after clicking the icon.

---

Any screenshots or videos of the bug would be helpful.

**Comment by Rayquaza01** [comment]
Sorry for the late reply. This should be a simple fix. `extension.getURL` seems to work differently on Linux than it does on Windows. There should be a fix out today or tomorrw.

Also this may be the same problem as #14.

**Comment by Rayquaza01** [comment]
@sirfz Does the new version fix the problem?

**Comment by sirfz** [comment]
Hi @Rayquaza01, still the same issue and error message with v1.2.1.

**Comment by Rayquaza01** [comment]
@sirfz OK, I think I figured out what is happening. For some reason, focusing a password input in the popup seem to make it close instantly. Changing it to a normal text input makes it work as normal. This doesn't happen in Windows, but for some reason it does in Ubuntu.

Could you try [this test version](https://github.com/Rayquaza01/authenticator/blob/master/two_factor_authenticator-2018.11.11-fx.xpi?raw=true) to see if it works before I publish it to AMO?

Thanks!

**Comment by sirfz** [comment]
Yes, the version you linked to fixed the problem!
