### ISSUE TITLE
Please sign the extention to be usable in Firefox 57 again

### ISSUE THREAD

**Issue by LutzBrandt** [Rayquaza01/authenticator#27]
## Feature Request

The extention seem not to be signed with Firefox so it cannot be used anymore in a vanilla FF installation version 57 onwards. According to the support page, the extention has to be signed to be installed again.
See https://support.mozilla.org/de/kb/Add-on-Signierung-in-Firefox?as=u&utm_source=inproduct#w_was-kainnen-sie-tun-wenn-firefox-ein-add-on-deaktiviert for the german help.

Thanks!

**Comment by Rayquaza01** [comment]
Hello,
Over the weekend, there was a bug with Mozilla's addon signing system that caused most addons to be disabled, despite being signed. They pushed a hotfix on Saturday, and an update to the browser last night that should have fixed this. See https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/.

All the extensions I have installed (including Authenticator) started working again after they pushed the fix, and it still says Authenticator is approved in the developer dashboard.
![Screenshot_2019-05-06 Status Versions Two Factor Authenticator Add-ons for Firefox](https://user-images.githubusercontent.com/22138871/57262883-24d81380-703c-11e9-982a-02c81ea68262.png)


Make sure you have the hotfix or the latest version of Firefox (66.0.4). If you do and you're still having the issue, you should probably contact Mozilla and tell them the fix didn't work for you.

Hope this helps!

**Comment by LutzBrandt** [comment]
Wow, thanks for the quick reply! Upgrading Firefox worked perfectly for me.
