### ISSUE TITLE
Hyphen in Display Name corrupts usage.

### ISSUE THREAD

**Issue by richard-scott** [Rayquaza01/authenticator#4]
I've added some sites that had hyphens in the site name. This has caused ALL previously added sites to not show up when clicking on the key icon. I had to export to json, edit that file to remove the offending item, re-import, quit FF and restart the browser to get it to work again.

**Comment by Rayquaza01** [comment]
Could you elaborate on how the hyphen is entered? A hyphen in the display name doesn't seem to cause problems on my end.

![image](https://user-images.githubusercontent.com/22138871/30833750-60c1c910-a21e-11e7-8910-2d6e4b93e44d.png)

There is a known bug where invalid secret keys can cause sites to not appear in the popup. Make sure you didn't accidentally mistype/mispaste the key.

**Comment by richard-scott** [comment]
Hmmm, maybe my key was incorrect then as your examples look like the ones I had that broke my setup.
e.g. Some-Site. Odd. I'll keep an eye on it.
