### ISSUE TITLE
Add sync, or possible way to copy the data file, or 2FA codes.

### ISSUE THREAD

**Issue by 0rkaM** [Rayquaza01/authenticator#8]
Hi there, I am trying your Firefox Addon on my ubuntu 16.04 laptop... and now the HD SMART is showing warning of imminent problem, so I need to copy (one way sync) the codes to my other desktop machine so not to loose my ability to log in into my accounts.
So in lack of a sync capability, or an interface to read and copy (or export/import) the file or codes, I would need to know where is a file I can copy over or read to get my 2FA TOTP codes out?
I tried to search about Firefox AddOns standard location and find the local profile folder and your code, but I could not find the data store, and since my HD could fail any time soon, I prefer no waste time and ask you directly.
Thank you very much.
Sincerely
Mark

**Comment by Rayquaza01** [comment]
On the options page, there should be a button below the configured sites labeled "Export". Clicking it should prompt you to download a file with your configuration which you can then import to your other machine.

Screenshot of options page for reference:
![](https://addons.cdn.mozilla.net/user-media/previews/full/190/190761.png)

**Comment by 0rkaM** [comment]
Wow... talking about blinds... I thought I looked well.
That works for me.
External sync would be nice... perhaps at a later date when file is encrypted.
Thank you
